gp_editor={sortable_area_sel:".gp_gallery",img_name:"gallery",img_rel:"gallery_gallery",edit_links_target:!1,auto_start:!1,make_sortable:!0,updateCaption:function(d,f){},removeImage:function(d){},removedImage:function(d){},addedImage:function(d){},editorLoaded:function(){},widthChanged:!1,heightChanged:!1,intervalSpeed:!1,moveBack:!1,moveForward:!1,checkDirty:function(){return!1},getData:function(d){var f={images:[],captions:[]};d.find(gp_editor.sortable_area_sel).find("li > a").each(function(){f.images.push($(this).attr("href"))});
d.find(gp_editor.edit_links_target).find(".caption").each(function(){f.captions.push($(this).html())});var m=$("#gp_gallery_options").find("input,select").serialize();d=d.clone();d.find("li.holder").remove();d.find("ul").enableSelection().removeClass("ui-sortable").removeAttr("unselectable");d.find(".gp_nosave").remove();d=d.html();return $.param(f)+"&"+m+"&gpcontent="+encodeURIComponent(d)},updateElement:function(){}};
function gp_init_inline_edit(d,f){function m(){function c(a,b,c){a.append('<a data-cmd="'+b+'"><img src="'+gpBase+'/include/imgs/blank.gif" height="16" width="16" class="'+c+'"/></a>')}g=h.find(gp_editor.sortable_area_sel);gp_editor.make_sortable&&q();gp_editor.resetDirty();strip_from(n,"?");gp_editing.editor_tools();$("#ckeditor_top").html('<div id="gp_image_area"></div><div id="gp_upload_queue"></div>');$("#ckeditor_controls").prepend('<div id="gp_folder_options"></div>');LoadImages(!1,gp_editor);
var b=$('<div id="gp_gallery_options">').prependTo("#ckeditor_save");if(gp_editor.heightChanged)$('<div class="half_width">'+gplang.Height+': <input class="ck_input" type="text" name="height" /></div>').appendTo(b).find("input").val(f.height).on("keyup paste change",gp_editor.heightChanged);gp_editor.widthChanged&&(debug(gp_editor.widthChanged),$('<div class="half_width">'+gplang.Width+': <input class="ck_input" type="text" name="width" /></div>').appendTo(b).find("input").val(f.width).on("keyup paste change",
gp_editor.widthChanged));gp_editor.auto_start&&(gplang.Auto_Start="Auto Start",$('<div class="half_width">'+gplang.Auto_Start+': <input class="ck_input" type="checkbox" name="auto_start" value="true" /></div>').appendTo(b).find("input").prop("checked",f.auto_start));gp_editor.intervalSpeed&&(gplang.Speed="Speed",$('<div class="half_width">'+gplang.Speed+': <input class="ck_input" type="text" name="interval_speed" /></div>').appendTo(b).find("input").val(f.interval_speed).on("keyup paste change",gp_editor.intervalSpeed));
e=$('<span class="gp_gallery_edit gp_floating_area"></span>').appendTo("body").hide();if(gp_editor.moveBack)$("<a>&lsaquo;</a>").appendTo(e).on("click",function(){gp_editor.moveBack(k)});if(gp_editor.moveForward)$("<a>&rsaquo;</a>").appendTo(e).on("click",function(){gp_editor.moveForward(k)});c(e,"gp_gallery_caption","page_edit");c(e,"gp_gallery_rm","delete");e.bind("mouseenter.gp_edit",function(){e.show()}).bind("mouseleave.gp_edit",function(){e.hide()});$(document).delegate(gp_editor.edit_links_target,
{"mousemove.gp_edit":function(){var a=$(this).offset();e.show().css({left:a.left,top:a.top});k=this},"mouseleave.gp_edit":function(){e.hide()},"mousedown.gp_edit":function(){e.hide()}});$gp.links.gp_gallery_caption=function(){e.hide();var a=$(k),a=a.find(".caption").html()||a.find("a:first").attr("title"),a='<div class="inline_box" id="gp_gallery_caption"><form><h3>'+gplang.cp+'</h3><textarea name="caption" cols="50" rows="3">'+$gp.htmlchars(a)+'</textarea><p><input type="submit" name="cmd" value="'+
gplang.up+'" class="gp_gallery_update" /> <input type="button" name="" value="'+gplang.ca+'" class="admin_box_close" /></p></form></div>';$gp.AdminBoxC(a)};$gp.links.gp_gallery_rm=function(){gp_editor.removeImage(k);$(k).remove();e.hide();gp_editor.removedImage(h)};gpinputs.gp_gallery_update=function(a){a.preventDefault();a=$(this.form).find("textarea").val();var b=$(k).find(".caption");b.html(a);a=b.html();$gp.CloseAdminBox();gp_editor.updateCaption(k,a)}}function q(){g.sortable({placeholder:"gp_drag_box",
opacity:0.6,tolerance:"pointer",beforeStop:function(c,b){b.item.removeAttr("style").removeAttr("class")}});g.disableSelection()}function p(c,b){h.find(".gp_to_remove").remove();c.attr({"data-cmd":gp_editor.img_name,"data-arg":gp_editor.img_rel,title:"","class":gp_editor.img_rel});var a=$("<li>").append(c).append('<div class="caption"></div>');b?b.replaceWith(a):g.append(a);a.trigger("gp_gallery_add");gp_editor.addedImage(a)}function r(c){c.attr("action");c.find(".file").auto_upload({start:function(b,
a){a.bar=$('<a data-cmd="gp_file_uploading">'+b+"</a>").appendTo("#gp_upload_queue");a.holder=$('<li class="holder" style="display:none"></li>').appendTo(g);return!0},progress:function(b,a,c){b=Math.round(100*b);b=Math.min(98,b-1);c.bar.text(b+"% "+a)},finish:function(b,a,c){var d=c.bar;d.text("100% "+a);var e=$(b);b=e.find(".status").val();e=e.find(".message").val();"success"==b?(d.addClass("success"),d.slideUp(1200),a=$("#gp_gallery_avail_imgs"),a=$(e).appendTo(a).find("a[name=gp_gallery_add],a[data-cmd=gp_gallery_add]"),
p(a.clone(),c.holder)):"notimage"==b?d.addClass("success"):(d.addClass("failed"),d.text(a+": "+e))},error:function(b,a,c){alert("error: "+c)}})}$gp.LoadStyle("/include/css/inline_image.css");"undefined"!==typeof gp_gallery_options&&$.extend(gp_editor,gp_gallery_options);gp_editor.edit_links_target||(gp_editor.edit_links_target=gp_editor.sortable_area_sel+" > li");var e=!1,l=!1,k=!1,g,n=gp_editing.get_path(d),h=gp_editing.get_edit_area(d);!1!=h&&!1!=n&&(gp_editor.save_path=n,gp_editor.destroy=function(){g.filter(":ui-sortable").sortable("destroy");
h.html(l.html());g.children("li").unbind("mouseenter.gp_edit, mouseleave.gp_edit, mousedown.gp_edit");e.remove()},gp_editor.checkDirty=function(){g.removeClass("ui-sortable");var c=l.html().replace(/>[\s]+/g,">"),b=h.html().replace(/>[\s]+/g,">");if(c!=b)return g.addClass("ui-sortable"),!0;g.addClass("ui-sortable");return!1},gp_editor.gp_saveData=function(){return gp_editor.getData(h,gp_editor)},gp_editor.resetDirty=function(){l=h.clone(!1);l.find(".ui-sortable").removeClass("ui-sortable")},h.get(0).innerHTML=
f.content,m(),gp_editor.editorLoaded(),$gp.links.gp_gallery_add=function(c){c.preventDefault();c=$(this).stop(!0,!0);p(c.clone());c.parent().fadeTo(100,0.2).fadeTo(2E3,1)},$gp.links.gp_gallery_add_all=function(c){c.preventDefault();$("#gp_gallery_avail_imgs").find("a[name=gp_gallery_add],a[data-cmd=gp_gallery_add]").each(function(b,a){p($(this).clone())})},gpresponse.gp_gallery_images=function(c){r($("#gp_upload_form"))},$gp.links.gp_file_uploading=function(){var c=$(this),b=!1;c.hasClass("failed")?
b=!0:c.hasClass("success")&&(b=!0);b&&c.slideUp(700)},gpinputs.gp_gallery_folder_add=function(c,b){b.preventDefault();var a=this.form;LoadImages(a.dir.value+"/"+a.newdir.value,gp_editor)})};