gp_editor={save_path:"?",saved_data:"",destroy:function(){},checkDirty:function(){var a=gp_editor.gp_saveData();return gp_editor.saved_data!=a?!0:!1},gp_saveData:function(){var a={section_order:[],attributes:[],contains_sections:[],cmd:"SaveSections"};$("#gpx_content").find(".editable_area").each(function(b){var c=$(this),d=gp_editor.TypeFromClass(this),e=c.data("gp-section");"undefined"==typeof e&&(e=d);a.section_order.push(e);a.attributes[b]=c.data("gp-attrs");"wrapper_section"==d&&(a.contains_sections[b]=
c.children(".editable_area").length)});return $.param(a)},resetDirty:function(){$("#gpx_content").find(".editable_area").each(function(a){$(this).data("gp-section",a).attr("data-gp-section",a).removeClass("new_section")});gp_editor.saved_data=gp_editor.gp_saveData()},updateElement:function(){},InitEditor:function(){$('<ul id="section_sorting" class="section_drag_area" style="overflow:auto">').appendTo("#ckeditor_top");gp_editor.resetDirty();gp_editor.InitSorting();gp_editor.InitNewSection();$gp.$win.on("resize",
gp_editor.MaxHeight).resize();$("#ckeditor_area").on("dragstop",gp_editor.MaxHeight)},MaxHeight:function(){var a=$("#ckeditor_area"),b=$("#section_sorting"),a=$gp.$win.height()-a.offset().top-a.height()+b.height()+$gp.$win.scrollTop();b.css("max-height",a)},InitNewSection:function(){$("#ckeditor_top").append(section_types)},InitSorting:function(){var a=$("#section_sorting").html(""),b=gp_editor.BuildSortHtml($("#gpx_content"));a.html(b);$(".section_drag_area").sortable({stop:gp_editor.DragStop,connectWith:".section_drag_area"}).disableSelection();
gp_editor.HoverListener(a)},BuildSortHtml:function(a){var b="";a.children(".editable_area").each(function(a){var d=$(this),e=gp_editor.TypeFromClass(this);b+='<li data-area-id="'+this.id+'">';b+='<div><span class="options">';b+='<a class="gpicon_edapp" data-cmd="SectionOptions" title="Options"></a>';b+='<a class="copy_icon" data-cmd="CopySection" title="Copy"></a>';b+='<a class="bin_icon RemoveSection" data-cmd="RemoveSection" title="Remove"></a>';b+="</span>";b+="<i>"+(a+1)+" "+gp_editor.ucfirst(e)+
"</i>";b+="</div>";"wrapper_section"==e&&(b+='<ul class="section_drag_area">',b+=gp_editor.BuildSortHtml(d),b+="</ul>");b+="</li>"});return b},DragStop:function(a,b){var c=gp_editor.GetArea(b.item),d=gp_editor.GetArea(b.item.prev());d.length?c.insertAfter(d):(d=b.item.parent().closest("ul"),"section_sorting"==d.attr("id")?c.prependTo("#gpx_content"):gp_editor.GetArea(d.parent()).prepend(c))},TypeFromClass:function(a){a=$(a).prop("class").substring(16);return a.substring(0,a.indexOf(" "))},HoverListener:function(a){a.find("div").hover(function(){var b=
$(this).parent();$(".section-item-hover").removeClass("section-item-hover");b.addClass("section-item-hover");$(".section-highlight").removeClass("section-highlight");gp_editor.GetArea(b).addClass("section-highlight")},function(){var b=$(this).parent();gp_editor.GetArea(b).removeClass("section-highlight");b.removeClass("section-item-hover")})},GetArea:function(a){a=a.data("area-id");return $("#"+a)},ucfirst:function(a){return a.charAt(0).toUpperCase()+a.slice(1)}};
$gp.response.AddSection=function(a){$("#gpx_content").append(a.CONTENT);gp_editor.InitSorting()};$gp.links.RemoveSection=function(a){1<$("#gpx_content").find(".editable_area").length&&(a=$(this).closest("li"),gp_editor.GetArea(a).remove(),a.remove())};$gp.links.CopySection=function(a){a=gp_editor.GetArea($(this).closest("li")).clone();var b="Copied_"+Math.floor(1E5*Math.random()+1)+"_"+a.attr("id");a.attr("id",b).addClass("new_section");$("#gpx_content").append(a);gp_editor.InitSorting()};
$gp.links.SectionOptions=function(a){var b=$(this).closest("li");a=b.data("area-id");b=gp_editor.GetArea(b).data("gp-attrs");html='<div class="inline_box"><form id="section_attributes_form" data-area-id="'+a+'">';html+="<h2>Section Attributes</h2>";html+='<table class="bordered full_width">';html+="<thead><tr><th>Attribute</th><th>Value</th></tr></thead><tbody>";$.each(b,function(b){b=b.toLowerCase();if("id"!=b&&"data-gp"!=b.substr(0,7)){var a=$.trim(this);if(""!=a||"class"==b)html+="<tr><td>",html+=
'<input class="gpinput attr_name" value="'+$gp.htmlchars(b)+'" size="8" />',html+='</td><td style="white-space:nowrap">',html+='<input class="gpinput attr_value" value="'+$gp.htmlchars(a)+'" size="40" />',"class"==b&&(html+='<div class="class_only admin_note">Default: GPAREA filetype-*</div>'),html+="</td></tr>"}});html+='<tr><td colspan="3">';html+='<a data-cmd="add_table_row">Add Attribute</a>';html+="</td></tr>";html+="</tbody></table>";html+="<p>";html+='<input type="button" name="" value="'+
gplang.up+'" class="gpsubmit" data-cmd="UpdateAttrs" /> ';html+='<input type="button" name="" value="'+gplang.ca+'" class="gpcancel" data-cmd="admin_box_close" />';html+="</p>";html+="</form></div>";$gp.AdminBoxC(html)};
$gp.inputs.UpdateAttrs=function(a){a.preventDefault();a=$("#section_attributes_form");var b=gp_editor.GetArea(a),c=b.data("gp-attrs"),d={},e=$("<div>");$.each(c,function(a){d[a]="";var c=b.attr(a)||"";e.attr("class",c);e.removeClass(""+this);b.attr(a,e.attr("class"))});a.find("tbody tr").each(function(){var a=$(this),c=a.find(".attr_name").val(),a=a.find(".attr_value").val();if((c=$.trim(c).toLowerCase())&&"id"!=c&&"data-gp"!=c.substr(0,7)){var f=b.attr(c)||"";e.attr("class",f);e.addClass(a);b.attr(c,
e.attr("class"));d[c]=a}});b.data("gp-attrs",d);$gp.CloseAdminBox()};gp_editing.editor_tools();gp_editor.InitEditor();loaded();