var gp_editor=!1,debug_area;function debug(a){debug_area||(debug_area=$('<div id="debug" style="position:absolute;top:0;left:0;background:#fff;padding:10px;z-index:99999;border:1px solid #333;max-width:30%;white-space:pre-wrap">').prependTo("body"));debug_area.prepend("<div>"+LOGO(a)+"</div><hr/>")}
function LOGO(a){var b,c=typeof a,d="\n<br/> ("+c+") ";if("object"===c)for(b in a){if(a.hasOwnProperty(b)){d+="\n<b>"+b+"</b> = ";try{d+=$gp.htmlchars(a[b])}catch(h){d+=" -- not allowed -- "}}}else d+=$gp.htmlchars(a);return d}$gp.Coords=function(a){a.hasClass("inner_size")&&(a=a.children(":first"));var b=a.offset();b.w=a.outerWidth();b.h=a.outerHeight();return b};$gp.div=function(a){var b=$("#"+a);0===b.length&&(b=$('<div id="'+a+'"></div>').appendTo("#gp_admin_html"));return b};
$gp.links.iadmin_box=function(a,b){a.preventDefault();$gp.CopyVals(b,this);$gp.AdminBoxC($(b),"inline")};
$gp.links.inline_edit_generic=function(a,b){a.preventDefault();$gp.loading();if("function"===typeof gplinks[b])gplinks[b].call(this,b,a);else{$gp.LoadStyle("/include/css/inline_edit.css");var c=strip_from(this.href,"#");if("manage_sections"==b)$gp.LoadStyle("/include/css/manage_sections.css");else var d=$(this).attr("id").substr(13),c=c+("&cmd=inlineedit&area_id="+d);$.getScript(c,function(a){"false"===a&&(alert($gp.error),$gp.loaded())})}};
$gp.links.remote=function(a){a.preventDefault();a=$gp.jPrep(this.href,"gpreq=body");if(gpRem){var b=window.location.href.split("/"),b=b[0]+"//"+b[2]+gpBase;0<window.location.href.indexOf("index.php")&&(b+="/index.php");a+="&inUrl="+encodeURIComponent(b)+"&gpRem="+encodeURIComponent(gpRem)}b=$gp.$win.height()-130;$gp.AdminBoxC('<iframe src="'+a+'" style="height:'+b+'px;" frameborder="0" />',{context:"iframe",width:780})};
$gp.LoadStyle=function(a){var b=(new Date).getTime();$('<link rel="stylesheet" type="text/css" />').appendTo("head").attr({href:gpBase+a+"?t="+b})};
$gp.AdminBoxC=function(a,b){$gp.CloseAdminBox();if(""===a)return!1;"string"==typeof b?b={context:b}:"undefined"==typeof b&&(b={});b=$.extend({context:"",width:640},b);var c=b.width,d=Math.round(($gp.$win.width()-c-40)/2),h=Math.max($gp.$doc.height(),$("body").outerHeight(!0));$gp.div("gp_admin_box1").css({zIndex:11E3,"min-height":h}).stop(!0,!0,!0).fadeTo(0,0).fadeTo(200,.2);$gp.div("gp_admin_box").css({zIndex:"11001",left:d,top:$gp.$win.scrollTop()}).stop(!0,!0,!0).fadeIn(400).html('<a class="gp_admin_box_close" data-cmd="admin_box_close"></a><div id="gp_admin_boxc" class="'+
(b.context||"")+'" style="width:'+c+'px"></div>').find("#gp_admin_boxc").html(a).find("input:visible:first").focus();$(".messages").detach();$gp.$doc.on("keypress.abox",function(a){27==a.keyCode&&$gp.CloseAdminBox()});return!0};
$gp.CloseAdminBox=function(a){a&&a.preventDefault();$gp.$doc.off("keypress.abox");$("#gp_admin_box1").fadeOut();$("#gp_admin_box").fadeOut(300,function(){$("#gp_admin_boxc").hasClass("inline")?$("#gp_admin_boxc").children().appendTo("#gp_hidden"):$("#gp_admin_boxc").children().remove()});"undefined"!==typeof $.fn.colorbox&&$.fn.colorbox.close()};$gp.links.admin_box_close=gpinputs.admin_box_close=$gp.CloseAdminBox;
$gp.SaveGPUI=function(){if(isadmin){var a="do=savegpui";$.each(gpui,function(b,c){a+="&gpui_"+b+"="+c});$gp.postC(window.location.href,a)}};
$gp.links.dd_menu=function(a){a.preventDefault();a.stopPropagation();$(".messages").detach();var b=this,c=$(this).parent().find(".dd_list");c.show();if(c.find(".selected").length){a=c.find("ul:first");var d=c.find(".selected").prev().prev().prev().position();d&&a.scrollTop(d.top+a.scrollTop())}$("body").on("click.gp_select",function(a){c.hide();c.off(".gp_select");$("body").off(".gp_select");$(a.target).closest(b).length&&a.stopPropagation()})};
$gp.links.tabs=function(a){a.preventDefault();a=$(this);a.siblings("a").removeClass("selected").each(function(a,c){c.hash&&$(c.hash).hide()});this.hash&&(a.addClass("selected"),$(this.hash).show())};$gp.Loaded={};$gp.LoadScripts=function(a,b,c){function d(){h--;0===h&&"function"===typeof b&&b.call(this)}var h=a.length,e=(new Date).getTime(),g="";c&&(g=gpBase);$.each(a,function(a,b){b=g+b;$gp.Loaded[b]?d():($gp.Loaded[b]=!0,$.getScript($gp.jPrep(b,"t="+e),function(){d()}))})};
$gp.links.gp_refresh=function(a){a.preventDefault();$gp.Reload()};$gp.links.toggle_panel=function(a){var b=$("#simplepanel");a.preventDefault();var c="";b.hasClass("minb")?(c="",a=0):b.hasClass("compact")?(c="minb toggledmin",a=3):(c="compact",a=1);b.hasClass("toggledmin")||b.unbind("mouseenter touchstart").bind("mouseenter touchstart",function(a){b.unbind(a).removeClass("toggledmin")});b.attr("class","keep_viewable "+c);gpui.cmpct=a;$gp.SaveGPUI()};
$gp.links.toplink=function(){var a=$(this);if(!$("#simplepanel").hasClass("compact")){var b=a.next(),c=b.is(":visible")&&0<b.height();$("#simplepanel .panelgroup2:visible").slideUp(300);gpui.vis=!1;c||(gpui.vis=a.data("arg"),b.slideDown(300));$gp.SaveGPUI()}};
$gp.links.collapsible=function(){var a=$(this).parent();a.hasClass("one")&&a.hasClass("gp_collapsed")?(a.parent().find(".head").addClass("gp_collapsed"),a.parent().find(".collapsearea").slideUp(300),a.removeClass("gp_collapsed").next().slideDown(300)):a.toggleClass("gp_collapsed").next().slideToggle(300)};
$gp.links.ajax_box=$gp.links.admin_box=function(a){alert(' "ajax_box" and "admin_box" are deprecated link arguments. Use gpabox instead.');a.preventDefault();$gp.loading();a=$gp.jPrep(this.href,"gpreq=flush");$.get(a,"",function(a){$gp.AdminBoxC(a);$gp.loaded()},"html")};$gp.links.gpabox=function(a){a.preventDefault();$gp.loading();a=$gp.jPrep(this.href)+"&gpx_content=gpabox";$.getJSON(a,$gp.Response)};
$gp.links.add_table_row=function(a){a=$(this).closest("tr");var b=a.closest("tbody").find("tr:first").clone();b.find(".class_only").remove();b.find("input").val("");a.before(b)};$gp.inputs.gpabox=function(){return $gp.post(this,"gpx_content=gpabox")};$gp.inputs.gpcheck=function(){this.checked?$(this).parent().addClass("checked"):$(this).parent().removeClass("checked")};$gp.inputs.check_all=function(){$(this).closest("form").find("input[type=checkbox]").prop("checked",this.checked)};
$gp.inputs.cnreq=function(a){a.preventDefault();a=$(this.form).serialize();$gp.Cookie("cookie_cmd",encodeURIComponent(a),1);window.location=strip_from(strip_from(this.form.action,"#"),"?")};$gp.htmlchars=function(a){a=a||"";return $("<a>").text(a).html()};$gp.response.location=function(a){window.setTimeout(function(){window.location=a.SELECTOR},a.CONTENT)};
$(function(){function a(){var a,b=$(this).find("ul");a=$gp.div("gp_edit_box");$("a.ExtraEditLink").clone(!1).attr("class","").css("display","block").show().each(function(){var c,g,f;g=$(this);var l=g.attr("id").substr(13);f=$("#ExtraEditArea"+l);if(f.hasClass("gp_no_overlay")||0===f.length)return!0;c=this.title.replace(/_/g," ");c=decodeURIComponent(c);15<c.length&&(c=c.substr(0,14)+"...");g.attr("id","editable_mark"+l).text(c).appendTo(b).wrap("<li>").on("mouseenter touchstart",function(){var b=
$gp.Coords(f);a.stop(!0,!0,!0).css({top:b.top-3,left:b.left-2,width:b.w+4,height:b.h+5}).fadeIn();($gp.$win.scrollTop()>b.top||$gp.$win.scrollTop()+$gp.$win.height()<b.top)&&$("html,body").stop(!0,!0,!0).animate({scrollTop:Math.max(0,b.top-100)},"slow")}).on("mouseleave touchend",function(){a.stop(!0,!0,!0).fadeOut()}).click(function(){$(this).unbind("mouseenter touchstart");window.setTimeout(function(){$(this).remove();a.hide()},100)})})}function b(){function a(b){b&&(b.hasClass("gp_editing")||b.removeClass("gp_no_overlay"))}
function b(){if(k&&!r){var a=k.offset(),c=k.position(),f=$gp.$win.scrollTop(),a=Math.max(0,f-(a.top-c.top));k.stop(!0,!0,!0).animate({top:a})}}function c(){p&&window.clearTimeout(p);p=window.setTimeout(function(){g()},200)}function g(){n=!1;m.find("span").stop(!0,!0).hide(500);m.find("div").stop(!0,!0).fadeOut()}function f(a){var c;if(!a.hasClass("gp_no_overlay")){c=a.attr("id").substr(13);var f=$("#ExtraEditLnks"+c).find("a");if(0===f.length&&(f=$("#ExtraEditLink"+c),0===f.length))return;c=$gp.Coords(a);
m.show().css({top:c.top-3,left:c.left-2,width:c.w+6});k?k.stop(!0,!0).show().removeClass("gp_hover"):(k=$("<span>"),q=$("<div>"),m.html(q).append(k));q.stop(!0,!0).hide().css({height:c.h+5,width:c.w+4});b();f=f.clone(!0).removeClass("ExtraEditLink");r=!1;k.css({left:"auto",top:0,right:0,position:"absolute"}).html('<a class="gp_overlay_expand"></a>').append(f).unbind("mouseenter touchstart").one("mouseenter touchstart",function(){a.hasClass("gp_no_overlay")||l()})}}function l(){k.addClass("gp_hover").stop(!0,
!0).show();q.stop(!0,!0).fadeIn()}var p=!1,m,k=!1,n,q,r=!1;m=$gp.div("gp_edit_overlay");m.click(function(a){var b=$(a.target);0<b.filter("a").length&&(b.hasClass("gp_overlay_close")&&a.preventDefault(),n&&n.addClass("gp_no_overlay"));g()}).on("mouseleave touchend",function(){c()}).on("mouseenter touchstart",function(){p&&window.clearTimeout(p)});$(".editable_area").bind("mousemove.gp mouseenter.gp touchstart.gp",function(b){p&&window.clearTimeout(p);var c=$(this);0<c.parent().closest(".editable_area").length&&
b.stopPropagation();n&&c.attr("id")===n.attr("id")||(n&&a(n),n=c,f(n))}).bind("mouseleave touchend",function(){c();a(n)});$gp.$win.scroll(function(){b()});$gp.$doc.on("contextmenu",".editable_area, #gp_edit_overlay",function(a){if(!(a.ctrlKey||a.altKey||a.shiftKey||gp_editor)&&k){a.preventDefault();l();var b=a.pageX-$gp.$win.scrollLeft(),c=b+k.width()-$gp.$win.width();0<c&&(b-=c);k.css({top:a.pageY-$gp.$win.scrollTop(),left:b,right:"auto",position:"fixed"});r=!0}})}function c(){SimpleDrag("#simplepanel .toolbar, #simplepanel .toolbar a",
"#simplepanel","fixed",function(a){gpui.tx=a.left;gpui.ty=a.top;$gp.SaveGPUI()},!0);$(".in_window").parent().bind("mouseenter touchstart",function(){var a=$(this).children(".in_window").css({right:"auto",left:"100%",top:0});window.setTimeout(function(){var b=a.offset(),c=b.left+a.width(),b=b.top+a.height();c>$gp.$win.width()+$gp.$win.scrollLeft()&&a.css({right:"100%",left:"auto"});c=$gp.$win.height()+$gp.$win.scrollTop();b>c&&a.css({top:c+-b-10})},1)})}$gp.$win=$(window);$gp.$doc=$(document);$gp.$doc.on("mousedown",
"form",function(){var a=$(this);"checked"!==a.data("gpForms")&&("undefined"!==typeof this["return"]&&(this["return"].value=window.location),a.data("gpForms","checked"))});isadmin&&"undefined"===typeof gp_bodyashtml&&($("body").addClass("gpAdmin").trigger("AdminReady"),window.setTimeout(function(){b();$("#editable_areas_list").one("mouseenter.edb touchstart.edb",a);c()},500),$gp.$doc.on("keyup keypress paste change",".show_character_count",function(){$(this).parent().find(".character_count span").html(this.value.length)}),
$gp.$win.on("beforeunload",function(){if(gp_editor&&"undefined"!==typeof gp_editor.checkDirty&&gp_editor.checkDirty())return"Unsaved changes will be lost."}))});
function SimpleDrag(a,b,c,d){function h(a,b){if(a.hasClass("keep_viewable")){var c,d={},e=a.position();if(b)a.data({gp_left:e.left,gp_top:e.top});else if(c=a.data("gp_left"))e.left=d.left=c,e.top=d.top=a.data("gp_top");c=a.width();var k=$gp.$win.height();-10>e.top?d.top=-10:e.top>k&&(d.top=k+-20);c=$gp.$win.width()-c- -10;e.left>c&&(d.left=c);(d.left||d.top)&&a.css(d)}}var e=$(b);$gp.$doc.off("mousedown.sdrag",a).on("mousedown.sdrag",a,function(a){function b(){var c=e.offset();h=a.clientX-c.left+
$gp.$win.scrollLeft();m=a.clientY-c.top+$gp.$win.scrollTop()}if(1==a.which){var l,h,m;a.preventDefault();if(!(1>e.length))return b(),$gp.$doc.bind("mousemove.sdrag",function(a){if(!l){var b=e.offset(),c=e.width(),f=e.height();l=$gp.div("admin_drag_box").css({top:b.top,left:b.left,width:c,height:f})}l.css({left:Math.max(-10,a.clientX-h),top:Math.max(-10,a.clientY-m)});a.preventDefault();return!1}),$gp.$doc.unbind("mouseup.sdrag").bind("mouseup.sdrag",function(a){var b,f,g;$gp.$doc.unbind("mousemove.sdrag mouseup.sdrag");
if(!l)return!1;a.preventDefault();l.remove();l=!1;b=a.clientX-h;f=a.clientY-m;"absolute"===c&&(b+=$gp.$win.scrollLeft(),f+=$gp.$win.scrollTop());b=Math.max(-10,b);f=Math.max(-10,f);g={left:b,top:f};e.css(g).data({gp_left:b,gp_top:f});"function"===typeof d&&d.call(e,g,a);e.trigger("dragstop");return!1}),!1}});"fixed"!==e.css("position")&&"fixed"!==e.parent().css("position")||h(e.addClass("keep_viewable"),!0);$gp.$win.resize(function(){$(".keep_viewable").each(function(){h($(this),!1)})})}
$gp.response.renameprep=function(){function a(){g.val().replace(/_/g," ").toLowerCase()!==e?$("#gp_rename_redirect").show(500):$("#gp_rename_redirect").hide(300)}function b(a){a.preventDefault();a=$(this).closest("td");var b=a.find("a:visible");a.find("a").show();b.hide();b=a.find("a:visible");b.length&&(b.hasClass("slug_edit")?(a.find("input").addClass("sync_label").prop("disabled","disabled").fadeTo(400,.6),c()):a.find("input").removeClass("sync_label").prop("disabled","").fadeTo(400,1))}function c(){var b=
$("input.title_label").val();$("input.new_title.sync_label").val(d(b));$("input.browser_title.sync_label").val(b);a();return!0}function d(a){a=a.replace(/[\x00-\x1F\x7F]/g,"");a=a.replace(/(\?|\*|:|#)/g,"");a=a.replace(/(<(\/?[a-zA-Z0-9][^<>]*)>)/ig,"");a=a.replace(/[\\]/g,"/");a=a.replace(/^\.+[\/\/]/,"/");a=a.replace(/[\/\/]\.+$/,"/");a=a.replace(/[\/\/]\.+[\/\/]/g,"/");a=a.replace(/[\/\/]+/g,"/");a="."===a?"":a.replace(/^\/\/*/g,"");return a.replace(/ /g,"_")}var h,e,g;(function(){h=$("#gp_rename_form");
e=h.find("input[name=old_title]").val().toLowerCase();g=$("input.new_title");c();$("input[disabled=disabled]").each(function(a,b){$(b).fadeTo(400,.6)});$("input.title_label").bind("keyup change",c);$(".label_synchronize a").click(b);$gp.links.showmore=function(){$("#gp_rename_table tr").show(500);$(this).parent().remove()};g.bind("keyup change",function(){a()})})()};
function SimpleResize(a,b){b=$.extend({},{max_w:1E4,min_w:0,finish:function(a,b){}},b);var c=$(a);if(!(1>c.length))$('<span class="gp_admin_resize"></span><span class="gp_admin_resize gp_resize_right"></span>').appendTo(c).on("mousedown.sres",function(a){if(1==a.which){var h=a.clientX,e=c.width(),g=e,f=c.position().left,l=f,p=$(this).hasClass("gp_resize_right"),m=new Date;a.preventDefault();$('<div style="position:fixed;top:0;right:0;bottom:0;left:0;cursor:e-resize;z-index:999000;">').appendTo("body").on("mousemove.sres",
function(a){var d=new Date;if(!(200>d-m))return m=d,p?e=a.clientX-h+g:(f=a.clientX-h+l,e=h-a.clientX+g,f=Math.max(0,f),c.css({left:f})),e=Math.min(b.max_w,e),e=Math.max(b.min_w,e),c.width(e).resize(),!1}).off("mouseup.sres").on("mouseup.sres",function(a){a.preventDefault();$(this).off("mousemove.sres mouseup.sres").remove();b.finish.call(c,e,f);return!1});return!1}})}
"function"!==typeof $.fn.disableSelection&&($.fn.disableSelection=function(){return $(this).attr("unselectable","on").css("-moz-user-select","none").each(function(){this.onselectstart=function(){return!1}})},$.fn.enableSelection=function(){return $(this).attr("unselectable","off").css("-moz-user-select","").each(function(){this.onselectstart=function(){return!1}})});