$(function(){function k(a){a=a.find("a.gp_label");return 0==a.length?"":a.data("arg")}function h(a){$(".current").removeClass("current");if(a.length){a.addClass("current");r(a);var b=e.height(),c=f.height();c<b&&f.css("min-height",b);if(a=a.position()){var d=0;0<a.top&&(d=Math.round(a.top/c*100));b=a.top-d/120*b;b=Math.max(0,b);e.stop().animate({top:b})}}else e.hide()}function r(a){var b=t,c=jQuery.extend({},a.find(".gp_label").data("json")),d=1<a.length;d?(c.key=a.find(".gp_label").map(function(){return $(this).data("arg")}).toArray().join(","),
c.files=a.length):a.find(".external").length&&(b=u);var c=$.extend({},{title:"",layout_color:"",layout_label:"",types:"",size:"",mtime:"",opts:""},c),q;$.each("title key url layout_label types size mtime opts files".split(" "),function(){q=new RegExp("(%5B"+this+"%5D|\\["+this+"\\])","gi");b=b.replace(q,c[this])});e.show().html(b).find(".layout_icon").css({background:c.layout_color});d?(e.find(".not_multiple").hide(),e.find(".only_multiple").show()):e.find(".only_multiple").hide();c.special&&e.find(".not_special").hide();
c.has_layout?e.find(".no_layout").hide():e.find(".has_layout").hide();c.level>=max_level_index&&e.find(".insert_child").hide()}function l(){var a,b,c=$("#admin_menu"),d={path:gpBLink+"/Admin_Menu",expires:100};if(0<c.length){a=v("gp_menu_hide")||"";a=decodeURIComponent(a);var e=$("#gp_curr_menu").val();a=a.replace(new RegExp("#"+e+"=\\[[^#=\\]\\[]*\\]",""),"");b="#"+$("#gp_curr_menu").val()+"=[";c.find(".hidechildren > div > .gp_label").each(function(a,c){b+=$(c).data("arg")+","});b+="]";$.cookie("gp_menu_hide",
a+b,d)}$.cookie("gp_menu_prefs",$("#gp_menu_select_form").serialize(),d)}function m(){var a,b,c="";$(".menu_marker").each(function(){var d=$(this);b=d.data("menuid");a=d.children();c+="&menus["+b+"]="+encodeURIComponent(a.eq(0).val());c+="&menuh["+b+"]="+encodeURIComponent(a.eq(1).val());c+="&menuc["+b+"]="+encodeURIComponent(a.eq(2).val())});return c}function v(a){a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];" "==d.charAt(0);)d=d.substring(1,d.length);if(0==d.indexOf(a))return d.substring(a.length,
d.length)}return!1}var f=$("#admin_menu"),e=$("#admin_menu_tools"),n=!1,p=!1,g=!1,t=$("#menu_info").html(),u=$("#menu_info_extern").html();f.nestedSortable({disableNesting:"no-nest",forcePlaceholderSize:!0,handle:"a.sort",items:"li",opacity:.8,placeholder:"placeholder",tabSize:25,toleranceElement:"> div",listType:"ul",delay:2,stop:function(a,b){var c=b.item,d=c.parent().siblings("div"),e=c.children("div"),c={cmd:"drag",drag_key:k(e),parent:k(d),prev:k(c.prev().children("div")),hidden:c.closest("#menu_available_list").length};
0<d.length&&d.parent(":not(.haschildren)").addClass("haschildren");0<g.length&&0==g.find("li").length&&g.removeClass("haschildren");h(e);$gp.loading();c=jQuery.param(c,!0);c+=m();$gp.postC(window.location.href,c)},start:function(a,b){g=b.item.parent().siblings("div").parent()}}).disableSelection();gpresponse.gp_menu_prep=function(){var a=$(".current:first");n=a.attr("id");p=$("#admin_menu .gp_label").index(a.find(".gp_label"))};gpresponse.gp_menu_refresh=function(a){f.nestedSortable("refresh");if(n)var b=
$("#"+n);b.length||(0<p&&(b=$("#admin_menu .gp_label").eq(p).parent()),b.length||(b=$(".gp_label:first").parent()));h(b)};$gp.links.menu_info=function(a){a.preventDefault();var b=$(this),c=b.parent();if(a.ctrlKey)c.toggleClass("current"),c=$(".current");else if(a.shiftKey){$(".current").removeClass("current");a=$("#admin_menu .gp_label");var b=a.index(this),d=0,e=$(".last_clicked");e.length&&(d=a.index(e));var f=Math.min(b,d),g=Math.max(b,d);a.each(function(a){a>=f&&a<=g&&$(this).parent().addClass("current")});
c=$(".current")}else $(".last_clicked").removeClass("last_clicked"),b.addClass("last_clicked");window.setTimeout(function(){h(c)},100)};$gp.links.expand_img=function(a){$gp.links.menu_info.call(this,a);$li=$(this).closest("li");$li.hasClass("haschildren")&&($li.toggleClass("hidechildren"),l())};gpinputs.menupost=function(){var a=m(),b=$(this).closest("form");b.attr("action",$gp.jPrep(b.attr("action"),a));$gp.post(this);return!1};$gp.links.menupost=function(a){a.preventDefault();a=strip_to(this.search,
"?");a+=m();$gp.postC(this.href,a)};$("#gp_menu_select").change(function(){l();var a=window.location.href;a.indexOf("?")?window.location=strip_from(a,"?"):$gp.Reload()});$(document).on("click","input:checkbox",function(){$this=$(this);0<$this.filter(":checked").length?$this.closest("li").addClass("gpui-state-checked"):$this.closest("li").removeClass("gpui-state-checked")});$(document).on("keyup","input.gpsearch",function(){var a=this.value.toLowerCase();$(this).closest("form").find(".gpui-scrolllist li:not(.gpui-state-checked)").each(function(){var b=
$(this);-1==b.text().toLowerCase().indexOf(a)?b.hide():b.show()})});(function(){var a=$("#admin_menu").find("div:first");h(a);l()})()});