var $gp={inputs:{},response:{},error:"There was an error processing the last request. Please reload this page to continue.",jGoTo:function(a){$gp.loading();a=$gp.jPrep(a);$.getJSON(a,$gp.Response)},cGoTo:function(a,b){var d=$(a),d=a.search+"&verified="+encodeURIComponent(d.data("nonce"));$gp.Cookie("cookie_cmd",encodeURIComponent(d),1);b?$gp.Reload():window.location=strip_from(strip_from(a.href,"#"),"?")},post:function(a,b){$gp.loading();var d=$(a).closest("form"),c=d.serialize()+"&verified="+encodeURIComponent(post_nonce);
if("INPUT"===a.nodeName||"BUTTON"===a.nodeName)c+="&"+encodeURIComponent(a.name)+"="+encodeURIComponent(a.value);b&&(c+="&"+b);$.post($gp.jPrep(d.attr("action")),c,$gp.Response,"json");return!1},post_link:function(a){$gp.loading();var b=$(a),b=strip_to(a.search,"?")+"&gpreq=json&jsoncallback=?&verified="+encodeURIComponent(b.data("nonce"));$.post(strip_from(a.href,"?"),b,$gp.Response,"json")},postC:function(a,b,d,c){d=d||$gp.Response;c=c||"json";"object"===typeof b&&(b=$.param(b));b+="&verified="+
encodeURIComponent(post_nonce);"json"===c&&(b+="&gpreq=json&jsoncallback=?");$.post(strip_from(a,"?"),b,d,c)},cboxSettings:function(a){a=a||{};"object"!=typeof colorbox_lang&&(colorbox_lang={});return $.extend(colorbox_lang,{opacity:.75,maxWidth:"90%",maxHeight:"90%"},a)},Cookie:function(a,b,d){var c="";d&&(c=new Date,c.setTime(c.getTime()+864E5*d),c="; expires="+c.toGMTString());document.cookie=a+"="+b+c+"; path=/"},jPrep:function(a,b){b="undefined"===typeof b?"gpreq=json&jsoncallback=?":b;a=strip_from(a,
"#");a+=-1===a.indexOf("?")?"?":"&";return a+b},Response:function(a,b,d){$(".messages").detach();try{$gp.CloseAdminBox()}catch(c){}try{$.fn.colorbox.close()}catch(e){}$.each(a,function(a,c){if("function"===typeof $gp.response[c.DO])$gp.response[c.DO].call(this,c,b,d);else if("function"===typeof gpresponse[c.DO])gpresponse[c.DO].call(this,c,b,d);else{switch(c.DO){case "replace":$(c.SELECTOR).replaceWith(c.CONTENT);break;case "inner":$(c.SELECTOR).html(c.CONTENT);break;case "admin_box_data":$gp.AdminBoxC(c.CONTENT);
break;case "messages":$(c.CONTENT).appendTo("body").show().css({top:0})}var e=$(c.SELECTOR);if("function"==typeof e[c.DO])e[c.DO](c.CONTENT)}});$gp.loaded()},loading:function(){var a=$("#loading1");0==a.length&&(a=$('<div id="loading1"/>').appendTo("body"));a.css("zIndex",99E3).fadeIn()},loaded:function(){$("#loading1").clearQueue().fadeOut()},CopyVals:function(a,b){var d=$(a).find("form").get(0);d&&$(b).find("input").each(function(a,b){d[b.name]&&(d[b.name].value=b.value)})},Reload:function(){typeof req_type&&
"post"==req_type?window.location.href=strip_from(window.location.href,"#"):window.location.reload(!0)},links:{gallery:function(a,b){a.preventDefault();b=""===b?this:"a[rel="+b+"],a."+b;$.colorbox.remove();$(b).colorbox($gp.cboxSettings({resize:!0,rel:b}));$(this).trigger("click.cbox")}}};$gp.Cookie("cookie_cmd","",-1);
$(function(){function a(a){$(a).filter("[method=post]").append('<input type="hidden" name="verified" value="'+post_nonce+'" />')}var b=$(document);$("body").addClass("STCLASS");b.ajaxError(function(a,b,e,f){$gp.loaded();"abort"!=b.statusText&&"function"!==typeof e.error&&""!=f&&(a={thrownError:f,responseText:b.responseText,responseStatus:b.status,statusText:b.statusText,url:e.url,type:e.type,browser:navigator.userAgent},window.console&&console.log&&console.log(a),"undefined"===typeof debugjs?alert($gp.error):
!0===debugjs&&"function"===typeof debug?(e.data&&(a.data=e.data.substr(0,100)),debug(a)):"send"===debugjs&&(alert($gp.error),e.data&&(a.data=e.data),a.cmd="javascript_error",$.ajax({type:"POST",url:"http://www.gpeasy.com/Resources",data:a,success:function(){},error:function(){}})))});b.on("click","input,button",function(b){a(this.form);var c=$(this);if(!c.hasClass("gpvalidate")||"function"!=typeof this.form.checkValidity||this.form.checkValidity())if(c.hasClass("gpconfirm")&&!confirm(this.title))b.preventDefault();
else{var e=c.data("cmd");e||(e=strip_from(c.attr("class")," "));if("function"===typeof $gp.inputs[e])return $gp.inputs[e].call(this,b);if("function"===typeof gpinputs[e])return gpinputs[e].call(this,b,b);switch(e){case "gppost":case "gpajax":return b.preventDefault(),$gp.post(this)}return!0}});b.on("submit","form",function(){a(this)});b.delegate(".expand_child",{mouseenter:function(){var a=$(this).addClass("expand");a.hasClass("simple_top")&&a.addClass("simple_top_hover")},mouseleave:function(){$(this).removeClass("expand simple_top_hover")}});
b.on("click","a",function(a){var b=$(this),e=b.data("cmd"),f=b.data("arg");e||(e=b.attr("name"),f=b.attr("rel"));if(b.hasClass("gpconfirm")&&!confirm(this.title))a.preventDefault();else{if("function"===typeof $gp.links[e])return $gp.links[e].call(this,a,f);if("function"===typeof gplinks[e])return gplinks[e].call(this,f,a);switch(e){case "toggle_show":$(f).toggle();break;case "inline_box":$gp.CopyVals(f,this);$.fn.colorbox($gp.cboxSettings({inline:!0,href:f,open:!0}));break;case "postlink":$gp.post_link(this);
break;case "gpajax":$gp.jGoTo(this.href);break;case "creq":$gp.cGoTo(this,!0);break;case "cnreq":$gp.cGoTo(this,!1);break;case "close_message":b.closest("div").slideUp();break;default:return!0}a.preventDefault();return!1}});$("body").trigger("gpReady")});function strip_to(a,b){if(!a)return a;var d=a.indexOf(b);return-1<d?a.substr(d+1):a}function strip_from(a,b){if(!a)return a;var d=a.indexOf(b);0<d&&(a=a.substr(0,d));return a}function jPrep(a,b){return $gp.jPrep(a,b)}
function ajaxResponse(a,b,d){return $gp.Response(a,b,d)}function loading(){$gp.loading()}function loaded(){$gp.loaded()};